name: Update Marka Listesi
on:
  schedule:
    - cron: '0 0 * * *' # Her gün gece yarısı çalışır (UTC zaman dilimi)
  workflow_dispatch: # Manuel tetikleme için (isteğe bağlı)
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install xml2js node-fetch@2
      - name: Run Update Script
        run: node update.js
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Marka listesi güncellendi" || echo "Değişiklik yok"
          git push
